import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from "axios";
import DefaulUrl from './DefaultUrl';

const initialState = {
  statusC: "",
  statusN: "",
  categoryList: [],
  newsList: [],
};

export const getCategoryAsync = createAsyncThunk(
  'news/fetchCategoryList',
  async () => {

    const hasil = await axios.get(`${DefaulUrl}&countries=us`);
    return hasil.data;
  }
);

export const getAntrianAsync = createAsyncThunk(
  'news/fetchNewsList',
  async () => {

    const hasil = await axios.get(`${DefaulUrl}&countries=us`);
    return hasil.data;
  }
);

export const NewsSlice = createSlice({
  name: 'product',
  initialState,
  reducers: {
    /* dataFilter: (state, action) => {
      // const parameter = action.payload;
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      let filter = {
        "kodeproduk": ["CWT 01"],
        "id": [78, 7169],
      };
    }, */

    /* // Use the PayloadAction type to declare the contents of `action.payload`
    drawerposisi: (state, action) => {
      state.status = action.payload;
    }, */
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCategoryAsync.pending, (state) => {
        state.pesanC = 'loading';
      })
      .addCase(getCategoryAsync.rejected, (state) => {
        state.pesanC = 'rejected';
      })
      .addCase(getCategoryAsync.fulfilled, (state, action) => {
        state.pesanC = 'idle';
        state.categoryList = action.payload;
      })
      .addCase(getAntrianAsync.pending, (state) => {
        state.pesanN = 'loading';
      })
      .addCase(getAntrianAsync.rejected, (state) => {
        state.pesanN = 'rejected';
      })
      .addCase(getAntrianAsync.fulfilled, (state, action) => {
        state.pesanN = 'idle';
        state.newsList = action.payload;
      });
  },
});

export const { dataFilter } = NewsSlice.actions;

export const selectPesanC = (state) => state.productcs.pesanC;
export const selectPensanN = (state) => state.productcs.pesanN;
export const categories = (state) => state.productcs.categoryList;
export const news = (state) => state.productcs.newsList;

export default NewsSlice.reducer;
